// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhs37XMwDfZk58dFKMVSCyvSUbUbwerhQ',
    appId: '1:632124694509:web:b9667e92de05705c3811e4',
    messagingSenderId: '632124694509',
    projectId: 'signlanguagetool',
    authDomain: 'signlanguagetool.firebaseapp.com',
    storageBucket: 'signlanguagetool.appspot.com',
    measurementId: 'G-GGD3JZWLD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5tjDmlLBI7G2Zfl4F09k3fQdO1WTIgM',
    appId: '1:632124694509:android:a185cfd682f067e03811e4',
    messagingSenderId: '632124694509',
    projectId: 'signlanguagetool',
    storageBucket: 'signlanguagetool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWxPVbI_ynqlHKogDRBBArJm60kqx_PA',
    appId: '1:632124694509:ios:1a2b1f4ae1f2ed0b3811e4',
    messagingSenderId: '632124694509',
    projectId: 'signlanguagetool',
    storageBucket: 'signlanguagetool.appspot.com',
    iosBundleId: 'com.example.signLanguageTool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgWxPVbI_ynqlHKogDRBBArJm60kqx_PA',
    appId: '1:632124694509:ios:1a2b1f4ae1f2ed0b3811e4',
    messagingSenderId: '632124694509',
    projectId: 'signlanguagetool',
    storageBucket: 'signlanguagetool.appspot.com',
    iosBundleId: 'com.example.signLanguageTool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhs37XMwDfZk58dFKMVSCyvSUbUbwerhQ',
    appId: '1:632124694509:web:12ebd11f0282ffa43811e4',
    messagingSenderId: '632124694509',
    projectId: 'signlanguagetool',
    authDomain: 'signlanguagetool.firebaseapp.com',
    storageBucket: 'signlanguagetool.appspot.com',
    measurementId: 'G-JXD1K7WFR6',
  );
}
